import type { Event, RecordCategory } from '@/types';

export function getDefaultEvents(): Event[] {
  const now = new Date().toISOString();
  
  return [
    {
      id: crypto.randomUUID(),
      name: 'Staff Meeting',
      category: 'adult',
      description: 'Regular staff meeting',
      isDefault: true,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      name: 'Training Session',
      category: 'adult',
      description: 'Staff training session',
      isDefault: true,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      name: 'Weekly Service',
      category: 'adult',
      description: 'Weekly church service',
      isDefault: true,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      name: 'Special Event',
      category: 'adult',
      description: 'Special church event',
      isDefault: true,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      name: 'Youth Meeting',
      category: 'youth',
      description: 'Regular youth group meeting',
      isDefault: true,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      name: 'Bible Study',
      category: 'youth',
      description: 'Youth bible study session',
      isDefault: true,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      name: 'Fellowship',
      category: 'youth',
      description: 'Youth fellowship gathering',
      isDefault: true,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      name: 'Outreach',
      category: 'youth',
      description: 'Youth outreach activity',
      isDefault: true,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      name: 'Sports Activity',
      category: 'youth',
      description: 'Youth sports event',
      isDefault: true,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      name: 'Adult Bible Study',
      category: 'adolescent',
      description: 'Adult bible study session',
      isDefault: true,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      name: 'Prayer Meeting',
      category: 'adolescent',
      description: 'Adult prayer meeting',
      isDefault: true,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      name: 'Fellowship',
      category: 'adolescent',
      description: 'Adult fellowship gathering',
      isDefault: true,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      name: 'Workshop',
      category: 'adolescent',
      description: 'Adult workshop session',
      isDefault: true,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      name: 'Sunday School',
      category: 'child',
      description: 'Children Sunday school',
      isDefault: true,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      name: "Children's Service",
      category: 'child',
      description: 'Children church service',
      isDefault: true,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      name: 'Activity Day',
      category: 'child',
      description: 'Children activity day',
      isDefault: true,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      name: 'Special Program',
      category: 'child',
      description: 'Special children program',
      isDefault: true,
      createdAt: now,
    },
  ];
}
